name: Audora frontend

on: 
  push: 
    branches: [ master ]
    paths: 
      - 'apps/audora-frontend/**'
      - 'packages/**'
      - '.github/workflows/cd_frontend.yml'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code frontend
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/frontend.prod.Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
            NEXT_PUBLIC_NEXTAUTH_URL=${{ secrets.NEXT_PUBLIC_NEXTAUTH_URL }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/audora-frontend:${{ github.sha }} 
            ${{ secrets.DOCKERHUB_USERNAME }}/audora-frontend:latest

#       - name: Deploy to VM
#         uses: appleboy/ssh-action@v1.2.0
#         with:
#           host: "${{secrets.HOST_IP}}"
#           username: "ubuntu"
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: 22
#           script: |
#             sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/audora-frontend:latest

#             if sudo docker ps -a --format '{{.Names}}' | grep -q "^audora-frontend$"; then
#               sudo docker stop audora-frontend
#               sudo docker rm audora-frontend
#             fi

#             sudo docker run -d \
#               --name audora-frontend \
#               -p 3000:3000 \
#               --restart always \
#               ${{ secrets.DOCKERHUB_USERNAME }}/audora-frontend:latest

#             echo "Audora frontend deployed successfully!"
#             sudo docker image prune -f --filter "until=24h"