name: Audora Signal

on: 
  push: 
    branches: [ master ]
    paths: 
      - 'apps/audora-signal/**'
      - 'packages/**'
      - '.github/workflows/cd_signal.yml'

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code signal
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/signal.prod.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/audora-signal:${{ github.sha }} 
            ${{ secrets.DOCKERHUB_USERNAME }}/audora-signal:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: "${{secrets.HOST_IP}}"
          username: "ubuntu"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/audora-signal:latest

            if sudo docker ps -a --format '{{.Names}}' | grep -q "^audora-signal$"; then
              sudo docker stop audora-signal
              sudo docker rm audora-signal
            fi

            sudo docker run -d \
              --name audora-signal \
              -e NODE_ENV=production \
              -e NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -p 8000:8000 \
              --restart always \
              ${{ secrets.DOCKERHUB_USERNAME }}/audora-signal:latest

            echo "Audora Signal deployed successfully!"
            sudo docker image prune -f --filter "until=24h"